[project]
name = "ai-product-crm-multiagent"
version = "0.1.0"
dependencies = [
    "fastmcp>=2.14.1",
    "mcp>=1.29.1,<2.0",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*", "graph*", "nodes*","utils*"]
